version: '3.8'

services:
  db_old:
  # mysql version tbd
    image: mysql:8.0.36
    container_name: db_old
    environment:
    # pw secrets tbd
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/old_root_password
      MYSQL_DATABASE: moodle_old
      MYSQL_USER: moodle
      MYSQL_PASSWORD_FILE: /run/secrets/moodle_password
    secrets: 
      - old_root_password
      - moodle_password
    volumes:
      - db_old_data:/var/lib/mysql

  old_moodle:
    image: bitnami/moodle:3.10.4
    container_name: old_moodle
    environment:
      - MOODLE_DOCKER_DBTYPE=mysqli
      - MOODLE_DOCKER_DBHOST=db_old
      - MOODLE_DOCKER_DBNAME=moodle_old
      - MOODLE_DOCKER_DBUSER=moodle
      - MOODLE_DOCKER_DBPASS: /run/secrets/moodle_password
    secrets: 
      - moodle_password
    ports:
      - "80:80"
    depends_on:
      - db_old
    volumes:
      - old_moodle_data:/var/www/html

  db_new:
   # evt mariadb?
    image: mysql:8.4.0
    container_name: db_new
    environment:
    # pw tbd - evt secrets
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/new_root_password
      MYSQL_DATABASE: moodle_new
      MYSQL_USER: moodle
      MYSQL_PASSWORD_FILE: /run/secrets/moodle_password
      # volume tbd - weil wir den db zwischenschritt manuell machen
    secrets: 
      - new_root_password
      - moodle_password
    volumes:
      - db_new_data:/var/lib/mysql
      
  new_moodle:
    image: bitnami/moodle:4.4.0
    container_name: new_moodle
    environment:
      - MOODLE_DOCKER_DBTYPE=mysqli
      - MOODLE_DOCKER_DBHOST=db_new
      - MOODLE_DOCKER_DBNAME=moodle_new
      - MOODLE_DOCKER_DBUSER=moodle
      - MOODLE_DOCKER_DBPASS_FILE: /run/secrets/moodle_password
    secrets:
      - moodle_password
    ports:
      - "443:80"
    depends_on:
      - db_new
    volumes:
      - new_moodle_data:/var/www/html

secrets:
  old_root_password:
    file: ${HOME}/secrets/old_root_password.txt
  moodle_password: 
    file: ${HOME}/secrets/moodle_password.txt
  new_root_password:
    file: ${HOME}/secrets/new_root_password.txt

volumes:
  db_old_data:
  db_new_data:
  old_moodle_data:
  new_moodle_data: