version: '3.8'

services:

# DB-Container des alten Moodles
  db_old:
    image: moodledb_old
    container_name: db_old
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/old_root_password
      MYSQL_DATABASE: moodle_old
      MYSQL_USER: moodle
      MYSQL_PASSWORD_FILE: /run/secrets/moodle_password
    secrets: 
      - old_root_password
      - moodle_password
    volumes:
      - db_old_data:/var/lib/mysql
    networks:
      - moodle-old
      
# Container des alten Moodles
  old_moodle:
    image: bitnami/moodle:3.10.4
    container_name: old_moodle
    environment:
      - MOODLE_DOCKER_DBTYPE=mysqli
      - MOODLE_DOCKER_DBHOST=db_old
      - MOODLE_DOCKER_DBNAME=moodle_old
      - MOODLE_DOCKER_DBUSER=moodle
      - MOODLE_DOCKER_DBPASS: /run/secrets/moodle_password
    secrets: 
      - moodle_password
    ports:
      - "8080:80"
    depends_on:
      - db_old
    volumes:
      - old_moodle_data:/var/www/html
    networks:
      - moodle-old

# DB-Container des neuen Moodles
  db_new:
    image: moodledb_new
    container_name: db_new
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/new_root_password
      MYSQL_DATABASE: moodle_new
      MYSQL_USER: moodle
      MYSQL_PASSWORD_FILE: /run/secrets/moodle_password
    secrets: 
      - new_root_password
      - moodle_password
    volumes:
      - db_new_data:/var/lib/mysql
    networks:
      - moodle-new
      
# Container des neuen Moodles
  new_moodle:
    image: bitnami/moodle:4.4.0
    container_name: new_moodle
    environment:
      - MOODLE_DOCKER_DBTYPE=mysqli
      - MOODLE_DOCKER_DBHOST=db_new
      - MOODLE_DOCKER_DBNAME=moodle_new
      - MOODLE_DOCKER_DBUSER=moodle
      - MOODLE_DOCKER_DBPASS_FILE: /run/secrets/moodle_password
    secrets:
      - moodle_password
    ports:
      - "80:80"
    depends_on:
      - db_new
    volumes:
      - new_moodle_data:/var/www/html
    networks:
      - moodle-new

# Definierung aller Secrets
secrets:
  old_root_password:
    file: ${HOME}/secrets/old_root_password.txt
  moodle_password: 
    file: ${HOME}/secrets/moodle_password.txt
  new_root_password:
    file: ${HOME}/secrets/new_root_password.txt

# Referenzierung aller Volumes
volumes:
  db_old_data:
  db_new_data:
  old_moodle_data:
  new_moodle_data: