version: "3.8"
services:
  db_new:
    image: moodledb_new
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/new_root_password
      MYSQL_DATABASE: moodle_new
      MYSQL_USER: moodle
      MYSQL_PASSWORD_FILE: /run/secrets/moodle_password
    secrets: 
      - new_root_password
      - moodle_password
    volumes:
      - db_new_data:/var/lib/mysql
    networks:
      - moodle-new
  
  new_moodle:
    image: bitnami/moodle:4.4.0
    environment:
      MOODLE_DATABASE_HOST: db_new
      MOODLE_DATABASE_NAME: moodle_new
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD_FILE: /run/secrets/moodle_password
    ports:
      - "80:80"
    depends_on:
      - db_new
    volumes:
      - moodle-data:/bitnami/moodle
      - dbdata:/bitnami/moodledata
    networks:
      - moodle-new
secrets:
  new_root_password:
    file: M158-main/secrets/new_root_password.txt
  moodle_password:
    file: M158-main/secrets/moodle_password.txt

volumes:
  db_new_data:
  moodle-data:
  dbdata:

networks:
  moodle-new: