version: "3.8"
services:
  db_new:
    image: bitnami/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: moodle_new
      MYSQL_USER: moodle
      MYSQL_PASSWORD: test
    volumes:
      - db_new_data:/var/lib/mysql
    networks:
      - moodle-new
  
  new_moodle:
    image: bitnami/moodle:4.4.0
    environment:
      MOODLE_DATABASE_HOST: db_new
      MOODLE_DATABASE_NAME: moodle_new
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: test
    ports:
      - "80:8080"
    depends_on:
      - db_new
    volumes:
      - moodle-data:/bitnami/moodle
      - dbdata:/bitnami/moodledata
    networks:
      - moodle-new

volumes:
  db_new_data:
  moodle-data:
  dbdata:

networks:
  moodle-new: