version: "4.0"
services:
  db_old:
    image: bitnami/mariadb
    environment:
      MARIADB_ROOT_PASSWORD: MuMissduP1434!
      MARIADB_DATABASE: moodle_old
      MARIADB_USER: moodle
      MARIADB_PASSWORD: Riethuesli>12345678910!
    volumes:
      - db_old_data:/bitnami/mariadb
    networks:
      - moodle-network-old
  
  new_moodle:
    image: bitnami/moodle:3.11.12
    environment:
      MOODLE_DATABASE_HOST: db_old
      MOODLE_DATABASE_NAME: moodle_old
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: Riethuesli>12345678910!
    ports:
      - "8080:8080"
    depends_on:
      - db_old
    volumes:
      - moodle-data:/bitnami/moodle
      - dbdata:/bitnami/moodledata
    networks:
      - moodle-network-old
  phpmyadmin: 
    image: phpmyadmin
    restart: always
    ports:
      - "8088:80"
    environment:
      - PMA_HOST=db_old
    networks:
      - moodle-network-old

volumes:
  db_old_data:
  moodle-data:
  dbdata:

networks:
  moodle-network-old:
